// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://locdutpzcotamsvtqjqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2R1dHB6Y290YW1zdnRxanFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTcwMzUsImV4cCI6MjA3MTA5MzAzNX0.mHJL_NeE5q1--kLLnvT8nuKjlVIHhehhPxsxBzF8BqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});